apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: data-generator
  labels:
    app: data-generator
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: data-generator
  labels:
    app: data-generator
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.jvm
  output:
    to:
      kind: ImageStreamTag
      name: data-generator:latest
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: replicate-redis
  labels:
    app: replicate-redis
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: replicate-redis
  labels:
    app: replicate-redis
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.jvm
  output:
    to:
      kind: ImageStreamTag
      name: replicate-redis:latest
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
