quarkus.redis.hosts=redis://localhost:6379
quarkus.kafka.devservices.enabled=false

mp.messaging.incoming.customer-events.connector=smallrye-kafka
mp.messaging.incoming.customer-events.topic=dbz.example_schema.customer
mp.messaging.incoming.customer-events.group.id=replicate-redis
mp.messaging.incoming.customer-events.bootstrap.servers=localhost:9092
mp.messaging.incoming.customer-events.auto.offset.reset=earliest
mp.messaging.incoming.customer-events.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.customer-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
